import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { normalizeSmsAudienceCriteria } from "@/lib/sms-audience-criteria";

const input = z.object({ id: z.string().uuid().optional(), name: z.string().min(2).max(120), description: z.string().max(300).optional(), criteria: z.record(z.string(), z.unknown()) });
async function tenant(s: any) { const { data, error } = await s.rpc("current_tenant_id"); if (error || !data) throw new Error("Tenant atual não encontrado."); return data; }
export const listSmsAudiences = createServerFn({ method: "GET" }).middleware([requireSupabaseAuth]).handler(async ({ context }) => { const s: any = context.supabase; const t = await tenant(s); const { data, error } = await s.from("sms_audiences").select("id,name,description,criteria,created_at,updated_at").eq("tenant_id", t).order("updated_at", { ascending: false }); if (error) throw new Error(error.message); return (data ?? []).map((row: any) => ({ ...row, criteria: normalizeSmsAudienceCriteria(row.criteria) })); });
export const saveSmsAudience = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).inputValidator((v: unknown) => input.parse(v)).handler(async ({ data, context }) => { const s: any = context.supabase; const tenantId = await tenant(s); const payload = { tenant_id: tenantId, name: data.name.trim(), description: data.description?.trim() || null, criteria: normalizeSmsAudienceCriteria(data.criteria), updated_at: new Date().toISOString() }; const q = data.id ? s.from("sms_audiences").update(payload).eq("id", data.id).eq("tenant_id", tenantId).select().single() : s.from("sms_audiences").insert(payload).select().single(); const { data: row, error } = await q; if (error) throw new Error(error.message); return row; });
export const deleteSmsAudience = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).inputValidator((v: unknown) => z.object({ id: z.string().uuid() }).parse(v)).handler(async ({ data, context }) => { const s: any = context.supabase; const t = await tenant(s); const { error } = await s.from("sms_audiences").delete().eq("id", data.id).eq("tenant_id", t); if (error) throw new Error(error.message); return { ok: true }; });
