import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Archive, Pencil, Play, Search, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { deleteJourneyVoiceAsset, getJourneyVoiceAssetPreview, listJourneyVoiceAssets, updateJourneyVoiceAsset } from "@/lib/journey-voice-assets.functions";

export function VoiceAssetsTab() {
  const qc = useQueryClient(); const list = useServerFn(listJourneyVoiceAssets); const preview = useServerFn(getJourneyVoiceAssetPreview); const update = useServerFn(updateJourneyVoiceAsset); const remove = useServerFn(deleteJourneyVoiceAsset);
  const [search, setSearch] = useState(""); const [editing, setEditing] = useState<any>(null); const [name, setName] = useState(""); const [tags, setTags] = useState(""); const [language, setLanguage] = useState("pt-BR");
  const assets = useQuery({ queryKey: ["journey-voice-assets"], queryFn: () => list() }); const refresh = () => qc.invalidateQueries({ queryKey: ["journey-voice-assets"] });
  const rows = useMemo(() => (assets.data?.assets ?? []).filter((a: any) => `${a.name} ${(a.tags ?? []).join(" ")} ${a.language}`.toLowerCase().includes(search.toLowerCase())), [assets.data, search]);
  const play = useMutation({ mutationFn: (id: string) => preview({ data: { id } }), onSuccess: ({ url }) => { const audio = new Audio(url); void audio.play(); }, onError: (e: Error) => toast.error(e.message) });
  const save = useMutation({ mutationFn: (asset: any) => update({ data: { id: asset.id, name, tags: tags.split(",").map((v) => v.trim()).filter(Boolean), language, isArchived: asset.is_archived } }), onSuccess: () => { setEditing(null); refresh(); toast.success("Metadados atualizados"); }, onError: (e: Error) => toast.error(e.message) });
  const action = useMutation({ mutationFn: async ({ kind, asset }: any) => kind === "delete" ? remove({ data: { id: asset.id } }) : update({ data: { id: asset.id, name: asset.name, tags: asset.tags ?? [], language: asset.language ?? "pt-BR", isArchived: !asset.is_archived } }), onSuccess: refresh, onError: (e: Error) => toast.error(e.message) });
  return <div className="space-y-4"><Card><CardHeader><CardTitle>Biblioteca de áudios</CardTitle></CardHeader><CardContent className="space-y-3 text-sm text-muted-foreground"><p>Ativos fixos reutilizáveis em jornadas e campanhas de voz. Arquive em vez de excluir quando houver retenção operacional.</p><div className="relative max-w-md"><Search className="absolute left-3 top-3 h-4 w-4" /><Input className="pl-9" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Buscar por nome, tag ou idioma" /></div></CardContent></Card>{rows.map((asset: any) => <Card key={asset.id} className={asset.is_archived ? "opacity-60" : ""}><CardContent className="flex flex-wrap items-center justify-between gap-3 p-4"><div><p className="font-medium">{asset.name}</p><p className="text-xs text-muted-foreground">{asset.language} · {asset.duration_seconds ? `${asset.duration_seconds}s · ` : ""}{Math.round(asset.size_bytes / 1024)} KB · {(asset.tags ?? []).join(", ") || "sem tags"}</p></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => play.mutate(asset.id)}><Play className="mr-1 h-3.5 w-3.5" />Ouvir</Button><Button size="sm" variant="outline" onClick={() => { setEditing(asset); setName(asset.name); setTags((asset.tags ?? []).join(", ")); setLanguage(asset.language ?? "pt-BR"); }}><Pencil className="mr-1 h-3.5 w-3.5" />Editar</Button><Button size="sm" variant="outline" onClick={() => action.mutate({ kind: "archive", asset })}><Archive className="mr-1 h-3.5 w-3.5" />{asset.is_archived ? "Reativar" : "Arquivar"}</Button><Button size="sm" variant="ghost" onClick={() => action.mutate({ kind: "delete", asset })}><Trash2 className="h-3.5 w-3.5" /></Button></div></CardContent></Card>)}{editing && <Card><CardHeader><CardTitle className="text-base">Editar metadados</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-3"><div><Label>Nome</Label><Input value={name} onChange={(e) => setName(e.target.value)} /></div><div><Label>Tags</Label><Input value={tags} onChange={(e) => setTags(e.target.value)} placeholder="vip, recuperação" /></div><div><Label>Idioma</Label><Input value={language} onChange={(e) => setLanguage(e.target.value)} /></div><div className="md:col-span-3 flex gap-2"><Button onClick={() => save.mutate(editing)} disabled={save.isPending}>Salvar</Button><Button variant="ghost" onClick={() => setEditing(null)}>Cancelar</Button></div></CardContent></Card>}</div>;
}
