/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as AutomacoesRouteImport } from './routes/automacoes'
import { Route as CampanhasRouteImport } from './routes/campanhas'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CreditosSmsRouteImport } from './routes/creditos-sms'
import { Route as EmailRouteImport } from './routes/email'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as ExpertsRouteImport } from './routes/experts'
import { Route as GamificacaoRouteImport } from './routes/gamificacao'
import { Route as InteligenciaRouteImport } from './routes/inteligencia'
import { Route as JornadasRouteImport } from './routes/jornadas'
import { Route as LigacoesRouteImport } from './routes/ligacoes'
import { Route as LinksRouteImport } from './routes/links'
import { Route as MidiaLtvRouteImport } from './routes/midia-ltv'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as PublicosRouteImport } from './routes/publicos'
import { Route as RegrasRouteImport } from './routes/regras'
import { Route as SmsRouteImport } from './routes/sms'
import { Route as TenantsRouteImport } from './routes/tenants'
import { Route as TreinoIaRouteImport } from './routes/treino-ia'
import { Route as WebhooksRouteImport } from './routes/webhooks'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as AutomacoesEmailRouteImport } from './routes/automacoes.email'
import { Route as AutomacoesLigacoesRouteImport } from './routes/automacoes.ligacoes'
import { Route as AutomacoesSmsRouteImport } from './routes/automacoes.sms'
import { Route as AutomacoesWhatsappRouteImport } from './routes/automacoes.whatsapp'
import { Route as JornadasJourneyIdRouteImport } from './routes/jornadas.$journeyId'
import { Route as JornadasNovaRouteImport } from './routes/jornadas.nova'
import { Route as PlayersPlayerIdRouteImport } from './routes/players.$playerId'
import { Route as UTokenRouteImport } from './routes/u.$token'
import { Route as ApiPublicEvolutionWebhookRouteImport } from './routes/api/public/evolution-webhook'
import { Route as ApiPublicSmsWebhookRouteImport } from './routes/api/public/sms-webhook'
import { Route as ApiPublicAutomationsDispatchRouteImport } from './routes/api/public/automations/dispatch'
import { Route as ApiPublicAutomationsEvaluateRouteImport } from './routes/api/public/automations/evaluate'
import { Route as ApiPublicCallFlowsTickRouteImport } from './routes/api/public/call-flows/tick'
import { Route as ApiPublicCallsBusinesscodeWebhookRouteImport } from './routes/api/public/calls/businesscode-webhook'
import { Route as ApiPublicDiagBusinesscodeEmailRouteImport } from './routes/api/public/diag/businesscode-email'
import { Route as ApiPublicDiagBusinesscodeSmsRouteImport } from './routes/api/public/diag/businesscode-sms'
import { Route as ApiPublicDiagBusinesscodeTokenCheckRouteImport } from './routes/api/public/diag/businesscode-token-check'
import { Route as ApiPublicDiagBusinesscodeVoiceRouteImport } from './routes/api/public/diag/businesscode-voice'
import { Route as ApiPublicDiagCallStatusRouteImport } from './routes/api/public/diag/call-status'
import { Route as ApiPublicEmailCampaignsTickRouteImport } from './routes/api/public/email-campaigns/tick'
import { Route as ApiPublicEmailFlowsTickRouteImport } from './routes/api/public/email-flows/tick'
import { Route as ApiPublicHooksCashbackCatchupRouteImport } from './routes/api/public/hooks/cashback-catchup'
import { Route as ApiPublicHooksDispatchRouteImport } from './routes/api/public/hooks/dispatch'
import { Route as ApiPublicHooksMorningCheckRouteImport } from './routes/api/public/hooks/morning-check'
import { Route as ApiPublicHooksOrchestrateRouteImport } from './routes/api/public/hooks/orchestrate'
import { Route as ApiPublicHooksRecoveryRouteImport } from './routes/api/public/hooks/recovery'
import { Route as ApiPublicHooksSmsRefreshStatusRouteImport } from './routes/api/public/hooks/sms-refresh-status'
import { Route as ApiPublicHooksWebhookReplayRouteImport } from './routes/api/public/hooks/webhook-replay'
import { Route as ApiPublicHooksWhatsappResumeRouteImport } from './routes/api/public/hooks/whatsapp-resume'
import { Route as ApiPublicMetaSyncTickRouteImport } from './routes/api/public/meta-sync/tick'
import { Route as ApiPublicPrecallDispatchRouteImport } from './routes/api/public/precall/dispatch'
import { Route as ApiPublicShortioSyncRouteImport } from './routes/api/public/shortio/sync'
import { Route as ApiPublicWebhookEventoRouteImport } from './routes/api/public/webhook.$evento'
import { Route as ApiPublicEmailImgAssetIdFilenameRouteImport } from './routes/api/public/email-img.$assetId.$filename'
import { Route as ApiPublicInfobipVoiceCmlRouteImport } from './routes/api/public/infobip/voice/cml'
import { Route as ApiPublicInfobipVoiceEventsRouteImport } from './routes/api/public/infobip/voice/events'
import { Route as ApiPublicWebhookTokenEventoRouteImport } from './routes/api/public/webhook.$token.$evento'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomacoesRoute = AutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanhasRoute = CampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditosSmsRoute = CreditosSmsRouteImport.update({
  id: '/creditos-sms',
  path: '/creditos-sms',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertsRoute = ExpertsRouteImport.update({
  id: '/experts',
  path: '/experts',
  getParentRoute: () => rootRouteImport,
} as any)
const GamificacaoRoute = GamificacaoRouteImport.update({
  id: '/gamificacao',
  path: '/gamificacao',
  getParentRoute: () => rootRouteImport,
} as any)
const InteligenciaRoute = InteligenciaRouteImport.update({
  id: '/inteligencia',
  path: '/inteligencia',
  getParentRoute: () => rootRouteImport,
} as any)
const JornadasRoute = JornadasRouteImport.update({
  id: '/jornadas',
  path: '/jornadas',
  getParentRoute: () => rootRouteImport,
} as any)
const LigacoesRoute = LigacoesRouteImport.update({
  id: '/ligacoes',
  path: '/ligacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const MidiaLtvRoute = MidiaLtvRouteImport.update({
  id: '/midia-ltv',
  path: '/midia-ltv',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicosRoute = PublicosRouteImport.update({
  id: '/publicos',
  path: '/publicos',
  getParentRoute: () => rootRouteImport,
} as any)
const RegrasRoute = RegrasRouteImport.update({
  id: '/regras',
  path: '/regras',
  getParentRoute: () => rootRouteImport,
} as any)
const SmsRoute = SmsRouteImport.update({
  id: '/sms',
  path: '/sms',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsRoute = TenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinoIaRoute = TreinoIaRouteImport.update({
  id: '/treino-ia',
  path: '/treino-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksRoute = WebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomacoesEmailRoute = AutomacoesEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AutomacoesRoute,
} as any)
const AutomacoesLigacoesRoute = AutomacoesLigacoesRouteImport.update({
  id: '/ligacoes',
  path: '/ligacoes',
  getParentRoute: () => AutomacoesRoute,
} as any)
const AutomacoesSmsRoute = AutomacoesSmsRouteImport.update({
  id: '/sms',
  path: '/sms',
  getParentRoute: () => AutomacoesRoute,
} as any)
const AutomacoesWhatsappRoute = AutomacoesWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AutomacoesRoute,
} as any)
const JornadasJourneyIdRoute = JornadasJourneyIdRouteImport.update({
  id: '/$journeyId',
  path: '/$journeyId',
  getParentRoute: () => JornadasRoute,
} as any)
const JornadasNovaRoute = JornadasNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => JornadasRoute,
} as any)
const PlayersPlayerIdRoute = PlayersPlayerIdRouteImport.update({
  id: '/$playerId',
  path: '/$playerId',
  getParentRoute: () => PlayersRoute,
} as any)
const UTokenRoute = UTokenRouteImport.update({
  id: '/u/$token',
  path: '/u/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEvolutionWebhookRoute =
  ApiPublicEvolutionWebhookRouteImport.update({
    id: '/api/public/evolution-webhook',
    path: '/api/public/evolution-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSmsWebhookRoute = ApiPublicSmsWebhookRouteImport.update({
  id: '/api/public/sms-webhook',
  path: '/api/public/sms-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAutomationsDispatchRoute =
  ApiPublicAutomationsDispatchRouteImport.update({
    id: '/api/public/automations/dispatch',
    path: '/api/public/automations/dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAutomationsEvaluateRoute =
  ApiPublicAutomationsEvaluateRouteImport.update({
    id: '/api/public/automations/evaluate',
    path: '/api/public/automations/evaluate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCallFlowsTickRoute = ApiPublicCallFlowsTickRouteImport.update({
  id: '/api/public/call-flows/tick',
  path: '/api/public/call-flows/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCallsBusinesscodeWebhookRoute =
  ApiPublicCallsBusinesscodeWebhookRouteImport.update({
    id: '/api/public/calls/businesscode-webhook',
    path: '/api/public/calls/businesscode-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDiagBusinesscodeEmailRoute =
  ApiPublicDiagBusinesscodeEmailRouteImport.update({
    id: '/api/public/diag/businesscode-email',
    path: '/api/public/diag/businesscode-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDiagBusinesscodeSmsRoute =
  ApiPublicDiagBusinesscodeSmsRouteImport.update({
    id: '/api/public/diag/businesscode-sms',
    path: '/api/public/diag/businesscode-sms',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDiagBusinesscodeTokenCheckRoute =
  ApiPublicDiagBusinesscodeTokenCheckRouteImport.update({
    id: '/api/public/diag/businesscode-token-check',
    path: '/api/public/diag/businesscode-token-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDiagBusinesscodeVoiceRoute =
  ApiPublicDiagBusinesscodeVoiceRouteImport.update({
    id: '/api/public/diag/businesscode-voice',
    path: '/api/public/diag/businesscode-voice',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDiagCallStatusRoute = ApiPublicDiagCallStatusRouteImport.update({
  id: '/api/public/diag/call-status',
  path: '/api/public/diag/call-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEmailCampaignsTickRoute =
  ApiPublicEmailCampaignsTickRouteImport.update({
    id: '/api/public/email-campaigns/tick',
    path: '/api/public/email-campaigns/tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEmailFlowsTickRoute = ApiPublicEmailFlowsTickRouteImport.update({
  id: '/api/public/email-flows/tick',
  path: '/api/public/email-flows/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCashbackCatchupRoute =
  ApiPublicHooksCashbackCatchupRouteImport.update({
    id: '/api/public/hooks/cashback-catchup',
    path: '/api/public/hooks/cashback-catchup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDispatchRoute = ApiPublicHooksDispatchRouteImport.update({
  id: '/api/public/hooks/dispatch',
  path: '/api/public/hooks/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksMorningCheckRoute =
  ApiPublicHooksMorningCheckRouteImport.update({
    id: '/api/public/hooks/morning-check',
    path: '/api/public/hooks/morning-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksOrchestrateRoute =
  ApiPublicHooksOrchestrateRouteImport.update({
    id: '/api/public/hooks/orchestrate',
    path: '/api/public/hooks/orchestrate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRecoveryRoute = ApiPublicHooksRecoveryRouteImport.update({
  id: '/api/public/hooks/recovery',
  path: '/api/public/hooks/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSmsRefreshStatusRoute =
  ApiPublicHooksSmsRefreshStatusRouteImport.update({
    id: '/api/public/hooks/sms-refresh-status',
    path: '/api/public/hooks/sms-refresh-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWebhookReplayRoute =
  ApiPublicHooksWebhookReplayRouteImport.update({
    id: '/api/public/hooks/webhook-replay',
    path: '/api/public/hooks/webhook-replay',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWhatsappResumeRoute =
  ApiPublicHooksWhatsappResumeRouteImport.update({
    id: '/api/public/hooks/whatsapp-resume',
    path: '/api/public/hooks/whatsapp-resume',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMetaSyncTickRoute = ApiPublicMetaSyncTickRouteImport.update({
  id: '/api/public/meta-sync/tick',
  path: '/api/public/meta-sync/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPrecallDispatchRoute =
  ApiPublicPrecallDispatchRouteImport.update({
    id: '/api/public/precall/dispatch',
    path: '/api/public/precall/dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicShortioSyncRoute = ApiPublicShortioSyncRouteImport.update({
  id: '/api/public/shortio/sync',
  path: '/api/public/shortio/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhookEventoRoute = ApiPublicWebhookEventoRouteImport.update({
  id: '/api/public/webhook/$evento',
  path: '/api/public/webhook/$evento',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEmailImgAssetIdFilenameRoute =
  ApiPublicEmailImgAssetIdFilenameRouteImport.update({
    id: '/api/public/email-img/$assetId/$filename',
    path: '/api/public/email-img/$assetId/$filename',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicInfobipVoiceCmlRoute =
  ApiPublicInfobipVoiceCmlRouteImport.update({
    id: '/api/public/infobip/voice/cml',
    path: '/api/public/infobip/voice/cml',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicInfobipVoiceEventsRoute =
  ApiPublicInfobipVoiceEventsRouteImport.update({
    id: '/api/public/infobip/voice/events',
    path: '/api/public/infobip/voice/events',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhookTokenEventoRoute =
  ApiPublicWebhookTokenEventoRouteImport.update({
    id: '/api/public/webhook/$token/$evento',
    path: '/api/public/webhook/$token/$evento',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alertas': typeof AlertasRoute
  '/automacoes': typeof AutomacoesRouteWithChildren
  '/campanhas': typeof CampanhasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/creditos-sms': typeof CreditosSmsRoute
  '/email': typeof EmailRoute
  '/eventos': typeof EventosRoute
  '/experts': typeof ExpertsRoute
  '/gamificacao': typeof GamificacaoRoute
  '/inteligencia': typeof InteligenciaRoute
  '/jornadas': typeof JornadasRouteWithChildren
  '/ligacoes': typeof LigacoesRoute
  '/links': typeof LinksRoute
  '/midia-ltv': typeof MidiaLtvRoute
  '/players': typeof PlayersRouteWithChildren
  '/publicos': typeof PublicosRoute
  '/regras': typeof RegrasRoute
  '/sms': typeof SmsRoute
  '/tenants': typeof TenantsRoute
  '/treino-ia': typeof TreinoIaRoute
  '/webhooks': typeof WebhooksRoute
  '/whatsapp': typeof WhatsappRoute
  '/automacoes/email': typeof AutomacoesEmailRoute
  '/automacoes/ligacoes': typeof AutomacoesLigacoesRoute
  '/automacoes/sms': typeof AutomacoesSmsRoute
  '/automacoes/whatsapp': typeof AutomacoesWhatsappRoute
  '/jornadas/$journeyId': typeof JornadasJourneyIdRoute
  '/jornadas/nova': typeof JornadasNovaRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/u/$token': typeof UTokenRoute
  '/api/public/evolution-webhook': typeof ApiPublicEvolutionWebhookRoute
  '/api/public/sms-webhook': typeof ApiPublicSmsWebhookRoute
  '/api/public/automations/dispatch': typeof ApiPublicAutomationsDispatchRoute
  '/api/public/automations/evaluate': typeof ApiPublicAutomationsEvaluateRoute
  '/api/public/call-flows/tick': typeof ApiPublicCallFlowsTickRoute
  '/api/public/calls/businesscode-webhook': typeof ApiPublicCallsBusinesscodeWebhookRoute
  '/api/public/diag/businesscode-email': typeof ApiPublicDiagBusinesscodeEmailRoute
  '/api/public/diag/businesscode-sms': typeof ApiPublicDiagBusinesscodeSmsRoute
  '/api/public/diag/businesscode-token-check': typeof ApiPublicDiagBusinesscodeTokenCheckRoute
  '/api/public/diag/businesscode-voice': typeof ApiPublicDiagBusinesscodeVoiceRoute
  '/api/public/diag/call-status': typeof ApiPublicDiagCallStatusRoute
  '/api/public/email-campaigns/tick': typeof ApiPublicEmailCampaignsTickRoute
  '/api/public/email-flows/tick': typeof ApiPublicEmailFlowsTickRoute
  '/api/public/hooks/cashback-catchup': typeof ApiPublicHooksCashbackCatchupRoute
  '/api/public/hooks/dispatch': typeof ApiPublicHooksDispatchRoute
  '/api/public/hooks/morning-check': typeof ApiPublicHooksMorningCheckRoute
  '/api/public/hooks/orchestrate': typeof ApiPublicHooksOrchestrateRoute
  '/api/public/hooks/recovery': typeof ApiPublicHooksRecoveryRoute
  '/api/public/hooks/sms-refresh-status': typeof ApiPublicHooksSmsRefreshStatusRoute
  '/api/public/hooks/webhook-replay': typeof ApiPublicHooksWebhookReplayRoute
  '/api/public/hooks/whatsapp-resume': typeof ApiPublicHooksWhatsappResumeRoute
  '/api/public/meta-sync/tick': typeof ApiPublicMetaSyncTickRoute
  '/api/public/precall/dispatch': typeof ApiPublicPrecallDispatchRoute
  '/api/public/shortio/sync': typeof ApiPublicShortioSyncRoute
  '/api/public/webhook/$evento': typeof ApiPublicWebhookEventoRoute
  '/api/public/email-img/$assetId/$filename': typeof ApiPublicEmailImgAssetIdFilenameRoute
  '/api/public/infobip/voice/cml': typeof ApiPublicInfobipVoiceCmlRoute
  '/api/public/infobip/voice/events': typeof ApiPublicInfobipVoiceEventsRoute
  '/api/public/webhook/$token/$evento': typeof ApiPublicWebhookTokenEventoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alertas': typeof AlertasRoute
  '/automacoes': typeof AutomacoesRouteWithChildren
  '/campanhas': typeof CampanhasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/creditos-sms': typeof CreditosSmsRoute
  '/email': typeof EmailRoute
  '/eventos': typeof EventosRoute
  '/experts': typeof ExpertsRoute
  '/gamificacao': typeof GamificacaoRoute
  '/inteligencia': typeof InteligenciaRoute
  '/jornadas': typeof JornadasRouteWithChildren
  '/ligacoes': typeof LigacoesRoute
  '/links': typeof LinksRoute
  '/midia-ltv': typeof MidiaLtvRoute
  '/players': typeof PlayersRouteWithChildren
  '/publicos': typeof PublicosRoute
  '/regras': typeof RegrasRoute
  '/sms': typeof SmsRoute
  '/tenants': typeof TenantsRoute
  '/treino-ia': typeof TreinoIaRoute
  '/webhooks': typeof WebhooksRoute
  '/whatsapp': typeof WhatsappRoute
  '/automacoes/email': typeof AutomacoesEmailRoute
  '/automacoes/ligacoes': typeof AutomacoesLigacoesRoute
  '/automacoes/sms': typeof AutomacoesSmsRoute
  '/automacoes/whatsapp': typeof AutomacoesWhatsappRoute
  '/jornadas/$journeyId': typeof JornadasJourneyIdRoute
  '/jornadas/nova': typeof JornadasNovaRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/u/$token': typeof UTokenRoute
  '/api/public/evolution-webhook': typeof ApiPublicEvolutionWebhookRoute
  '/api/public/sms-webhook': typeof ApiPublicSmsWebhookRoute
  '/api/public/automations/dispatch': typeof ApiPublicAutomationsDispatchRoute
  '/api/public/automations/evaluate': typeof ApiPublicAutomationsEvaluateRoute
  '/api/public/call-flows/tick': typeof ApiPublicCallFlowsTickRoute
  '/api/public/calls/businesscode-webhook': typeof ApiPublicCallsBusinesscodeWebhookRoute
  '/api/public/diag/businesscode-email': typeof ApiPublicDiagBusinesscodeEmailRoute
  '/api/public/diag/businesscode-sms': typeof ApiPublicDiagBusinesscodeSmsRoute
  '/api/public/diag/businesscode-token-check': typeof ApiPublicDiagBusinesscodeTokenCheckRoute
  '/api/public/diag/businesscode-voice': typeof ApiPublicDiagBusinesscodeVoiceRoute
  '/api/public/diag/call-status': typeof ApiPublicDiagCallStatusRoute
  '/api/public/email-campaigns/tick': typeof ApiPublicEmailCampaignsTickRoute
  '/api/public/email-flows/tick': typeof ApiPublicEmailFlowsTickRoute
  '/api/public/hooks/cashback-catchup': typeof ApiPublicHooksCashbackCatchupRoute
  '/api/public/hooks/dispatch': typeof ApiPublicHooksDispatchRoute
  '/api/public/hooks/morning-check': typeof ApiPublicHooksMorningCheckRoute
  '/api/public/hooks/orchestrate': typeof ApiPublicHooksOrchestrateRoute
  '/api/public/hooks/recovery': typeof ApiPublicHooksRecoveryRoute
  '/api/public/hooks/sms-refresh-status': typeof ApiPublicHooksSmsRefreshStatusRoute
  '/api/public/hooks/webhook-replay': typeof ApiPublicHooksWebhookReplayRoute
  '/api/public/hooks/whatsapp-resume': typeof ApiPublicHooksWhatsappResumeRoute
  '/api/public/meta-sync/tick': typeof ApiPublicMetaSyncTickRoute
  '/api/public/precall/dispatch': typeof ApiPublicPrecallDispatchRoute
  '/api/public/shortio/sync': typeof ApiPublicShortioSyncRoute
  '/api/public/webhook/$evento': typeof ApiPublicWebhookEventoRoute
  '/api/public/email-img/$assetId/$filename': typeof ApiPublicEmailImgAssetIdFilenameRoute
  '/api/public/infobip/voice/cml': typeof ApiPublicInfobipVoiceCmlRoute
  '/api/public/infobip/voice/events': typeof ApiPublicInfobipVoiceEventsRoute
  '/api/public/webhook/$token/$evento': typeof ApiPublicWebhookTokenEventoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alertas': typeof AlertasRoute
  '/automacoes': typeof AutomacoesRouteWithChildren
  '/campanhas': typeof CampanhasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/creditos-sms': typeof CreditosSmsRoute
  '/email': typeof EmailRoute
  '/eventos': typeof EventosRoute
  '/experts': typeof ExpertsRoute
  '/gamificacao': typeof GamificacaoRoute
  '/inteligencia': typeof InteligenciaRoute
  '/jornadas': typeof JornadasRouteWithChildren
  '/ligacoes': typeof LigacoesRoute
  '/links': typeof LinksRoute
  '/midia-ltv': typeof MidiaLtvRoute
  '/players': typeof PlayersRouteWithChildren
  '/publicos': typeof PublicosRoute
  '/regras': typeof RegrasRoute
  '/sms': typeof SmsRoute
  '/tenants': typeof TenantsRoute
  '/treino-ia': typeof TreinoIaRoute
  '/webhooks': typeof WebhooksRoute
  '/whatsapp': typeof WhatsappRoute
  '/automacoes/email': typeof AutomacoesEmailRoute
  '/automacoes/ligacoes': typeof AutomacoesLigacoesRoute
  '/automacoes/sms': typeof AutomacoesSmsRoute
  '/automacoes/whatsapp': typeof AutomacoesWhatsappRoute
  '/jornadas/$journeyId': typeof JornadasJourneyIdRoute
  '/jornadas/nova': typeof JornadasNovaRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/u/$token': typeof UTokenRoute
  '/api/public/evolution-webhook': typeof ApiPublicEvolutionWebhookRoute
  '/api/public/sms-webhook': typeof ApiPublicSmsWebhookRoute
  '/api/public/automations/dispatch': typeof ApiPublicAutomationsDispatchRoute
  '/api/public/automations/evaluate': typeof ApiPublicAutomationsEvaluateRoute
  '/api/public/call-flows/tick': typeof ApiPublicCallFlowsTickRoute
  '/api/public/calls/businesscode-webhook': typeof ApiPublicCallsBusinesscodeWebhookRoute
  '/api/public/diag/businesscode-email': typeof ApiPublicDiagBusinesscodeEmailRoute
  '/api/public/diag/businesscode-sms': typeof ApiPublicDiagBusinesscodeSmsRoute
  '/api/public/diag/businesscode-token-check': typeof ApiPublicDiagBusinesscodeTokenCheckRoute
  '/api/public/diag/businesscode-voice': typeof ApiPublicDiagBusinesscodeVoiceRoute
  '/api/public/diag/call-status': typeof ApiPublicDiagCallStatusRoute
  '/api/public/email-campaigns/tick': typeof ApiPublicEmailCampaignsTickRoute
  '/api/public/email-flows/tick': typeof ApiPublicEmailFlowsTickRoute
  '/api/public/hooks/cashback-catchup': typeof ApiPublicHooksCashbackCatchupRoute
  '/api/public/hooks/dispatch': typeof ApiPublicHooksDispatchRoute
  '/api/public/hooks/morning-check': typeof ApiPublicHooksMorningCheckRoute
  '/api/public/hooks/orchestrate': typeof ApiPublicHooksOrchestrateRoute
  '/api/public/hooks/recovery': typeof ApiPublicHooksRecoveryRoute
  '/api/public/hooks/sms-refresh-status': typeof ApiPublicHooksSmsRefreshStatusRoute
  '/api/public/hooks/webhook-replay': typeof ApiPublicHooksWebhookReplayRoute
  '/api/public/hooks/whatsapp-resume': typeof ApiPublicHooksWhatsappResumeRoute
  '/api/public/meta-sync/tick': typeof ApiPublicMetaSyncTickRoute
  '/api/public/precall/dispatch': typeof ApiPublicPrecallDispatchRoute
  '/api/public/shortio/sync': typeof ApiPublicShortioSyncRoute
  '/api/public/webhook/$evento': typeof ApiPublicWebhookEventoRoute
  '/api/public/email-img/$assetId/$filename': typeof ApiPublicEmailImgAssetIdFilenameRoute
  '/api/public/infobip/voice/cml': typeof ApiPublicInfobipVoiceCmlRoute
  '/api/public/infobip/voice/events': typeof ApiPublicInfobipVoiceEventsRoute
  '/api/public/webhook/$token/$evento': typeof ApiPublicWebhookTokenEventoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alertas'
    | '/automacoes'
    | '/campanhas'
    | '/configuracoes'
    | '/creditos-sms'
    | '/email'
    | '/eventos'
    | '/experts'
    | '/gamificacao'
    | '/inteligencia'
    | '/jornadas'
    | '/ligacoes'
    | '/links'
    | '/midia-ltv'
    | '/players'
    | '/publicos'
    | '/regras'
    | '/sms'
    | '/tenants'
    | '/treino-ia'
    | '/webhooks'
    | '/whatsapp'
    | '/automacoes/email'
    | '/automacoes/ligacoes'
    | '/automacoes/sms'
    | '/automacoes/whatsapp'
    | '/jornadas/$journeyId'
    | '/jornadas/nova'
    | '/players/$playerId'
    | '/u/$token'
    | '/api/public/evolution-webhook'
    | '/api/public/sms-webhook'
    | '/api/public/automations/dispatch'
    | '/api/public/automations/evaluate'
    | '/api/public/call-flows/tick'
    | '/api/public/calls/businesscode-webhook'
    | '/api/public/diag/businesscode-email'
    | '/api/public/diag/businesscode-sms'
    | '/api/public/diag/businesscode-token-check'
    | '/api/public/diag/businesscode-voice'
    | '/api/public/diag/call-status'
    | '/api/public/email-campaigns/tick'
    | '/api/public/email-flows/tick'
    | '/api/public/hooks/cashback-catchup'
    | '/api/public/hooks/dispatch'
    | '/api/public/hooks/morning-check'
    | '/api/public/hooks/orchestrate'
    | '/api/public/hooks/recovery'
    | '/api/public/hooks/sms-refresh-status'
    | '/api/public/hooks/webhook-replay'
    | '/api/public/hooks/whatsapp-resume'
    | '/api/public/meta-sync/tick'
    | '/api/public/precall/dispatch'
    | '/api/public/shortio/sync'
    | '/api/public/webhook/$evento'
    | '/api/public/email-img/$assetId/$filename'
    | '/api/public/infobip/voice/cml'
    | '/api/public/infobip/voice/events'
    | '/api/public/webhook/$token/$evento'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/alertas'
    | '/automacoes'
    | '/campanhas'
    | '/configuracoes'
    | '/creditos-sms'
    | '/email'
    | '/eventos'
    | '/experts'
    | '/gamificacao'
    | '/inteligencia'
    | '/jornadas'
    | '/ligacoes'
    | '/links'
    | '/midia-ltv'
    | '/players'
    | '/publicos'
    | '/regras'
    | '/sms'
    | '/tenants'
    | '/treino-ia'
    | '/webhooks'
    | '/whatsapp'
    | '/automacoes/email'
    | '/automacoes/ligacoes'
    | '/automacoes/sms'
    | '/automacoes/whatsapp'
    | '/jornadas/$journeyId'
    | '/jornadas/nova'
    | '/players/$playerId'
    | '/u/$token'
    | '/api/public/evolution-webhook'
    | '/api/public/sms-webhook'
    | '/api/public/automations/dispatch'
    | '/api/public/automations/evaluate'
    | '/api/public/call-flows/tick'
    | '/api/public/calls/businesscode-webhook'
    | '/api/public/diag/businesscode-email'
    | '/api/public/diag/businesscode-sms'
    | '/api/public/diag/businesscode-token-check'
    | '/api/public/diag/businesscode-voice'
    | '/api/public/diag/call-status'
    | '/api/public/email-campaigns/tick'
    | '/api/public/email-flows/tick'
    | '/api/public/hooks/cashback-catchup'
    | '/api/public/hooks/dispatch'
    | '/api/public/hooks/morning-check'
    | '/api/public/hooks/orchestrate'
    | '/api/public/hooks/recovery'
    | '/api/public/hooks/sms-refresh-status'
    | '/api/public/hooks/webhook-replay'
    | '/api/public/hooks/whatsapp-resume'
    | '/api/public/meta-sync/tick'
    | '/api/public/precall/dispatch'
    | '/api/public/shortio/sync'
    | '/api/public/webhook/$evento'
    | '/api/public/email-img/$assetId/$filename'
    | '/api/public/infobip/voice/cml'
    | '/api/public/infobip/voice/events'
    | '/api/public/webhook/$token/$evento'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alertas'
    | '/automacoes'
    | '/campanhas'
    | '/configuracoes'
    | '/creditos-sms'
    | '/email'
    | '/eventos'
    | '/experts'
    | '/gamificacao'
    | '/inteligencia'
    | '/jornadas'
    | '/ligacoes'
    | '/links'
    | '/midia-ltv'
    | '/players'
    | '/publicos'
    | '/regras'
    | '/sms'
    | '/tenants'
    | '/treino-ia'
    | '/webhooks'
    | '/whatsapp'
    | '/automacoes/email'
    | '/automacoes/ligacoes'
    | '/automacoes/sms'
    | '/automacoes/whatsapp'
    | '/jornadas/$journeyId'
    | '/jornadas/nova'
    | '/players/$playerId'
    | '/u/$token'
    | '/api/public/evolution-webhook'
    | '/api/public/sms-webhook'
    | '/api/public/automations/dispatch'
    | '/api/public/automations/evaluate'
    | '/api/public/call-flows/tick'
    | '/api/public/calls/businesscode-webhook'
    | '/api/public/diag/businesscode-email'
    | '/api/public/diag/businesscode-sms'
    | '/api/public/diag/businesscode-token-check'
    | '/api/public/diag/businesscode-voice'
    | '/api/public/diag/call-status'
    | '/api/public/email-campaigns/tick'
    | '/api/public/email-flows/tick'
    | '/api/public/hooks/cashback-catchup'
    | '/api/public/hooks/dispatch'
    | '/api/public/hooks/morning-check'
    | '/api/public/hooks/orchestrate'
    | '/api/public/hooks/recovery'
    | '/api/public/hooks/sms-refresh-status'
    | '/api/public/hooks/webhook-replay'
    | '/api/public/hooks/whatsapp-resume'
    | '/api/public/meta-sync/tick'
    | '/api/public/precall/dispatch'
    | '/api/public/shortio/sync'
    | '/api/public/webhook/$evento'
    | '/api/public/email-img/$assetId/$filename'
    | '/api/public/infobip/voice/cml'
    | '/api/public/infobip/voice/events'
    | '/api/public/webhook/$token/$evento'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AlertasRoute: typeof AlertasRoute
  AutomacoesRoute: typeof AutomacoesRouteWithChildren
  CampanhasRoute: typeof CampanhasRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  CreditosSmsRoute: typeof CreditosSmsRoute
  EmailRoute: typeof EmailRoute
  EventosRoute: typeof EventosRoute
  ExpertsRoute: typeof ExpertsRoute
  GamificacaoRoute: typeof GamificacaoRoute
  InteligenciaRoute: typeof InteligenciaRoute
  JornadasRoute: typeof JornadasRouteWithChildren
  LigacoesRoute: typeof LigacoesRoute
  LinksRoute: typeof LinksRoute
  MidiaLtvRoute: typeof MidiaLtvRoute
  PlayersRoute: typeof PlayersRouteWithChildren
  PublicosRoute: typeof PublicosRoute
  RegrasRoute: typeof RegrasRoute
  SmsRoute: typeof SmsRoute
  TenantsRoute: typeof TenantsRoute
  TreinoIaRoute: typeof TreinoIaRoute
  WebhooksRoute: typeof WebhooksRoute
  WhatsappRoute: typeof WhatsappRoute
  UTokenRoute: typeof UTokenRoute
  ApiPublicEvolutionWebhookRoute: typeof ApiPublicEvolutionWebhookRoute
  ApiPublicSmsWebhookRoute: typeof ApiPublicSmsWebhookRoute
  ApiPublicAutomationsDispatchRoute: typeof ApiPublicAutomationsDispatchRoute
  ApiPublicAutomationsEvaluateRoute: typeof ApiPublicAutomationsEvaluateRoute
  ApiPublicCallFlowsTickRoute: typeof ApiPublicCallFlowsTickRoute
  ApiPublicCallsBusinesscodeWebhookRoute: typeof ApiPublicCallsBusinesscodeWebhookRoute
  ApiPublicDiagBusinesscodeEmailRoute: typeof ApiPublicDiagBusinesscodeEmailRoute
  ApiPublicDiagBusinesscodeSmsRoute: typeof ApiPublicDiagBusinesscodeSmsRoute
  ApiPublicDiagBusinesscodeTokenCheckRoute: typeof ApiPublicDiagBusinesscodeTokenCheckRoute
  ApiPublicDiagBusinesscodeVoiceRoute: typeof ApiPublicDiagBusinesscodeVoiceRoute
  ApiPublicDiagCallStatusRoute: typeof ApiPublicDiagCallStatusRoute
  ApiPublicEmailCampaignsTickRoute: typeof ApiPublicEmailCampaignsTickRoute
  ApiPublicEmailFlowsTickRoute: typeof ApiPublicEmailFlowsTickRoute
  ApiPublicHooksCashbackCatchupRoute: typeof ApiPublicHooksCashbackCatchupRoute
  ApiPublicHooksDispatchRoute: typeof ApiPublicHooksDispatchRoute
  ApiPublicHooksMorningCheckRoute: typeof ApiPublicHooksMorningCheckRoute
  ApiPublicHooksOrchestrateRoute: typeof ApiPublicHooksOrchestrateRoute
  ApiPublicHooksRecoveryRoute: typeof ApiPublicHooksRecoveryRoute
  ApiPublicHooksSmsRefreshStatusRoute: typeof ApiPublicHooksSmsRefreshStatusRoute
  ApiPublicHooksWebhookReplayRoute: typeof ApiPublicHooksWebhookReplayRoute
  ApiPublicHooksWhatsappResumeRoute: typeof ApiPublicHooksWhatsappResumeRoute
  ApiPublicMetaSyncTickRoute: typeof ApiPublicMetaSyncTickRoute
  ApiPublicPrecallDispatchRoute: typeof ApiPublicPrecallDispatchRoute
  ApiPublicShortioSyncRoute: typeof ApiPublicShortioSyncRoute
  ApiPublicWebhookEventoRoute: typeof ApiPublicWebhookEventoRoute
  ApiPublicEmailImgAssetIdFilenameRoute: typeof ApiPublicEmailImgAssetIdFilenameRoute
  ApiPublicInfobipVoiceCmlRoute: typeof ApiPublicInfobipVoiceCmlRoute
  ApiPublicInfobipVoiceEventsRoute: typeof ApiPublicInfobipVoiceEventsRoute
  ApiPublicWebhookTokenEventoRoute: typeof ApiPublicWebhookTokenEventoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automacoes': {
      id: '/automacoes'
      path: '/automacoes'
      fullPath: '/automacoes'
      preLoaderRoute: typeof AutomacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanhas': {
      id: '/campanhas'
      path: '/campanhas'
      fullPath: '/campanhas'
      preLoaderRoute: typeof CampanhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creditos-sms': {
      id: '/creditos-sms'
      path: '/creditos-sms'
      fullPath: '/creditos-sms'
      preLoaderRoute: typeof CreditosSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experts': {
      id: '/experts'
      path: '/experts'
      fullPath: '/experts'
      preLoaderRoute: typeof ExpertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gamificacao': {
      id: '/gamificacao'
      path: '/gamificacao'
      fullPath: '/gamificacao'
      preLoaderRoute: typeof GamificacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inteligencia': {
      id: '/inteligencia'
      path: '/inteligencia'
      fullPath: '/inteligencia'
      preLoaderRoute: typeof InteligenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jornadas': {
      id: '/jornadas'
      path: '/jornadas'
      fullPath: '/jornadas'
      preLoaderRoute: typeof JornadasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ligacoes': {
      id: '/ligacoes'
      path: '/ligacoes'
      fullPath: '/ligacoes'
      preLoaderRoute: typeof LigacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/midia-ltv': {
      id: '/midia-ltv'
      path: '/midia-ltv'
      fullPath: '/midia-ltv'
      preLoaderRoute: typeof MidiaLtvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicos': {
      id: '/publicos'
      path: '/publicos'
      fullPath: '/publicos'
      preLoaderRoute: typeof PublicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regras': {
      id: '/regras'
      path: '/regras'
      fullPath: '/regras'
      preLoaderRoute: typeof RegrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sms': {
      id: '/sms'
      path: '/sms'
      fullPath: '/sms'
      preLoaderRoute: typeof SmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants': {
      id: '/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof TenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treino-ia': {
      id: '/treino-ia'
      path: '/treino-ia'
      fullPath: '/treino-ia'
      preLoaderRoute: typeof TreinoIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks': {
      id: '/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof WebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automacoes/email': {
      id: '/automacoes/email'
      path: '/email'
      fullPath: '/automacoes/email'
      preLoaderRoute: typeof AutomacoesEmailRouteImport
      parentRoute: typeof AutomacoesRoute
    }
    '/automacoes/ligacoes': {
      id: '/automacoes/ligacoes'
      path: '/ligacoes'
      fullPath: '/automacoes/ligacoes'
      preLoaderRoute: typeof AutomacoesLigacoesRouteImport
      parentRoute: typeof AutomacoesRoute
    }
    '/automacoes/sms': {
      id: '/automacoes/sms'
      path: '/sms'
      fullPath: '/automacoes/sms'
      preLoaderRoute: typeof AutomacoesSmsRouteImport
      parentRoute: typeof AutomacoesRoute
    }
    '/automacoes/whatsapp': {
      id: '/automacoes/whatsapp'
      path: '/whatsapp'
      fullPath: '/automacoes/whatsapp'
      preLoaderRoute: typeof AutomacoesWhatsappRouteImport
      parentRoute: typeof AutomacoesRoute
    }
    '/jornadas/$journeyId': {
      id: '/jornadas/$journeyId'
      path: '/$journeyId'
      fullPath: '/jornadas/$journeyId'
      preLoaderRoute: typeof JornadasJourneyIdRouteImport
      parentRoute: typeof JornadasRoute
    }
    '/jornadas/nova': {
      id: '/jornadas/nova'
      path: '/nova'
      fullPath: '/jornadas/nova'
      preLoaderRoute: typeof JornadasNovaRouteImport
      parentRoute: typeof JornadasRoute
    }
    '/players/$playerId': {
      id: '/players/$playerId'
      path: '/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof PlayersPlayerIdRouteImport
      parentRoute: typeof PlayersRoute
    }
    '/u/$token': {
      id: '/u/$token'
      path: '/u/$token'
      fullPath: '/u/$token'
      preLoaderRoute: typeof UTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/evolution-webhook': {
      id: '/api/public/evolution-webhook'
      path: '/api/public/evolution-webhook'
      fullPath: '/api/public/evolution-webhook'
      preLoaderRoute: typeof ApiPublicEvolutionWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sms-webhook': {
      id: '/api/public/sms-webhook'
      path: '/api/public/sms-webhook'
      fullPath: '/api/public/sms-webhook'
      preLoaderRoute: typeof ApiPublicSmsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/automations/dispatch': {
      id: '/api/public/automations/dispatch'
      path: '/api/public/automations/dispatch'
      fullPath: '/api/public/automations/dispatch'
      preLoaderRoute: typeof ApiPublicAutomationsDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/automations/evaluate': {
      id: '/api/public/automations/evaluate'
      path: '/api/public/automations/evaluate'
      fullPath: '/api/public/automations/evaluate'
      preLoaderRoute: typeof ApiPublicAutomationsEvaluateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/call-flows/tick': {
      id: '/api/public/call-flows/tick'
      path: '/api/public/call-flows/tick'
      fullPath: '/api/public/call-flows/tick'
      preLoaderRoute: typeof ApiPublicCallFlowsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/calls/businesscode-webhook': {
      id: '/api/public/calls/businesscode-webhook'
      path: '/api/public/calls/businesscode-webhook'
      fullPath: '/api/public/calls/businesscode-webhook'
      preLoaderRoute: typeof ApiPublicCallsBusinesscodeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/diag/businesscode-email': {
      id: '/api/public/diag/businesscode-email'
      path: '/api/public/diag/businesscode-email'
      fullPath: '/api/public/diag/businesscode-email'
      preLoaderRoute: typeof ApiPublicDiagBusinesscodeEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/diag/businesscode-sms': {
      id: '/api/public/diag/businesscode-sms'
      path: '/api/public/diag/businesscode-sms'
      fullPath: '/api/public/diag/businesscode-sms'
      preLoaderRoute: typeof ApiPublicDiagBusinesscodeSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/diag/businesscode-token-check': {
      id: '/api/public/diag/businesscode-token-check'
      path: '/api/public/diag/businesscode-token-check'
      fullPath: '/api/public/diag/businesscode-token-check'
      preLoaderRoute: typeof ApiPublicDiagBusinesscodeTokenCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/diag/businesscode-voice': {
      id: '/api/public/diag/businesscode-voice'
      path: '/api/public/diag/businesscode-voice'
      fullPath: '/api/public/diag/businesscode-voice'
      preLoaderRoute: typeof ApiPublicDiagBusinesscodeVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/diag/call-status': {
      id: '/api/public/diag/call-status'
      path: '/api/public/diag/call-status'
      fullPath: '/api/public/diag/call-status'
      preLoaderRoute: typeof ApiPublicDiagCallStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/email-campaigns/tick': {
      id: '/api/public/email-campaigns/tick'
      path: '/api/public/email-campaigns/tick'
      fullPath: '/api/public/email-campaigns/tick'
      preLoaderRoute: typeof ApiPublicEmailCampaignsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/email-flows/tick': {
      id: '/api/public/email-flows/tick'
      path: '/api/public/email-flows/tick'
      fullPath: '/api/public/email-flows/tick'
      preLoaderRoute: typeof ApiPublicEmailFlowsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/cashback-catchup': {
      id: '/api/public/hooks/cashback-catchup'
      path: '/api/public/hooks/cashback-catchup'
      fullPath: '/api/public/hooks/cashback-catchup'
      preLoaderRoute: typeof ApiPublicHooksCashbackCatchupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/dispatch': {
      id: '/api/public/hooks/dispatch'
      path: '/api/public/hooks/dispatch'
      fullPath: '/api/public/hooks/dispatch'
      preLoaderRoute: typeof ApiPublicHooksDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/morning-check': {
      id: '/api/public/hooks/morning-check'
      path: '/api/public/hooks/morning-check'
      fullPath: '/api/public/hooks/morning-check'
      preLoaderRoute: typeof ApiPublicHooksMorningCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/orchestrate': {
      id: '/api/public/hooks/orchestrate'
      path: '/api/public/hooks/orchestrate'
      fullPath: '/api/public/hooks/orchestrate'
      preLoaderRoute: typeof ApiPublicHooksOrchestrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/recovery': {
      id: '/api/public/hooks/recovery'
      path: '/api/public/hooks/recovery'
      fullPath: '/api/public/hooks/recovery'
      preLoaderRoute: typeof ApiPublicHooksRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sms-refresh-status': {
      id: '/api/public/hooks/sms-refresh-status'
      path: '/api/public/hooks/sms-refresh-status'
      fullPath: '/api/public/hooks/sms-refresh-status'
      preLoaderRoute: typeof ApiPublicHooksSmsRefreshStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/webhook-replay': {
      id: '/api/public/hooks/webhook-replay'
      path: '/api/public/hooks/webhook-replay'
      fullPath: '/api/public/hooks/webhook-replay'
      preLoaderRoute: typeof ApiPublicHooksWebhookReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/whatsapp-resume': {
      id: '/api/public/hooks/whatsapp-resume'
      path: '/api/public/hooks/whatsapp-resume'
      fullPath: '/api/public/hooks/whatsapp-resume'
      preLoaderRoute: typeof ApiPublicHooksWhatsappResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta-sync/tick': {
      id: '/api/public/meta-sync/tick'
      path: '/api/public/meta-sync/tick'
      fullPath: '/api/public/meta-sync/tick'
      preLoaderRoute: typeof ApiPublicMetaSyncTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/precall/dispatch': {
      id: '/api/public/precall/dispatch'
      path: '/api/public/precall/dispatch'
      fullPath: '/api/public/precall/dispatch'
      preLoaderRoute: typeof ApiPublicPrecallDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shortio/sync': {
      id: '/api/public/shortio/sync'
      path: '/api/public/shortio/sync'
      fullPath: '/api/public/shortio/sync'
      preLoaderRoute: typeof ApiPublicShortioSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhook/$evento': {
      id: '/api/public/webhook/$evento'
      path: '/api/public/webhook/$evento'
      fullPath: '/api/public/webhook/$evento'
      preLoaderRoute: typeof ApiPublicWebhookEventoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/email-img/$assetId/$filename': {
      id: '/api/public/email-img/$assetId/$filename'
      path: '/api/public/email-img/$assetId/$filename'
      fullPath: '/api/public/email-img/$assetId/$filename'
      preLoaderRoute: typeof ApiPublicEmailImgAssetIdFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/infobip/voice/cml': {
      id: '/api/public/infobip/voice/cml'
      path: '/api/public/infobip/voice/cml'
      fullPath: '/api/public/infobip/voice/cml'
      preLoaderRoute: typeof ApiPublicInfobipVoiceCmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/infobip/voice/events': {
      id: '/api/public/infobip/voice/events'
      path: '/api/public/infobip/voice/events'
      fullPath: '/api/public/infobip/voice/events'
      preLoaderRoute: typeof ApiPublicInfobipVoiceEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhook/$token/$evento': {
      id: '/api/public/webhook/$token/$evento'
      path: '/api/public/webhook/$token/$evento'
      fullPath: '/api/public/webhook/$token/$evento'
      preLoaderRoute: typeof ApiPublicWebhookTokenEventoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AutomacoesRouteChildren {
  AutomacoesEmailRoute: typeof AutomacoesEmailRoute
  AutomacoesLigacoesRoute: typeof AutomacoesLigacoesRoute
  AutomacoesSmsRoute: typeof AutomacoesSmsRoute
  AutomacoesWhatsappRoute: typeof AutomacoesWhatsappRoute
}

const AutomacoesRouteChildren: AutomacoesRouteChildren = {
  AutomacoesEmailRoute: AutomacoesEmailRoute,
  AutomacoesLigacoesRoute: AutomacoesLigacoesRoute,
  AutomacoesSmsRoute: AutomacoesSmsRoute,
  AutomacoesWhatsappRoute: AutomacoesWhatsappRoute,
}

const AutomacoesRouteWithChildren = AutomacoesRoute._addFileChildren(
  AutomacoesRouteChildren,
)

interface JornadasRouteChildren {
  JornadasJourneyIdRoute: typeof JornadasJourneyIdRoute
  JornadasNovaRoute: typeof JornadasNovaRoute
}

const JornadasRouteChildren: JornadasRouteChildren = {
  JornadasJourneyIdRoute: JornadasJourneyIdRoute,
  JornadasNovaRoute: JornadasNovaRoute,
}

const JornadasRouteWithChildren = JornadasRoute._addFileChildren(
  JornadasRouteChildren,
)

interface PlayersRouteChildren {
  PlayersPlayerIdRoute: typeof PlayersPlayerIdRoute
}

const PlayersRouteChildren: PlayersRouteChildren = {
  PlayersPlayerIdRoute: PlayersPlayerIdRoute,
}

const PlayersRouteWithChildren =
  PlayersRoute._addFileChildren(PlayersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AlertasRoute: AlertasRoute,
  AutomacoesRoute: AutomacoesRouteWithChildren,
  CampanhasRoute: CampanhasRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  CreditosSmsRoute: CreditosSmsRoute,
  EmailRoute: EmailRoute,
  EventosRoute: EventosRoute,
  ExpertsRoute: ExpertsRoute,
  GamificacaoRoute: GamificacaoRoute,
  InteligenciaRoute: InteligenciaRoute,
  JornadasRoute: JornadasRouteWithChildren,
  LigacoesRoute: LigacoesRoute,
  LinksRoute: LinksRoute,
  MidiaLtvRoute: MidiaLtvRoute,
  PlayersRoute: PlayersRouteWithChildren,
  PublicosRoute: PublicosRoute,
  RegrasRoute: RegrasRoute,
  SmsRoute: SmsRoute,
  TenantsRoute: TenantsRoute,
  TreinoIaRoute: TreinoIaRoute,
  WebhooksRoute: WebhooksRoute,
  WhatsappRoute: WhatsappRoute,
  UTokenRoute: UTokenRoute,
  ApiPublicEvolutionWebhookRoute: ApiPublicEvolutionWebhookRoute,
  ApiPublicSmsWebhookRoute: ApiPublicSmsWebhookRoute,
  ApiPublicAutomationsDispatchRoute: ApiPublicAutomationsDispatchRoute,
  ApiPublicAutomationsEvaluateRoute: ApiPublicAutomationsEvaluateRoute,
  ApiPublicCallFlowsTickRoute: ApiPublicCallFlowsTickRoute,
  ApiPublicCallsBusinesscodeWebhookRoute:
    ApiPublicCallsBusinesscodeWebhookRoute,
  ApiPublicDiagBusinesscodeEmailRoute: ApiPublicDiagBusinesscodeEmailRoute,
  ApiPublicDiagBusinesscodeSmsRoute: ApiPublicDiagBusinesscodeSmsRoute,
  ApiPublicDiagBusinesscodeTokenCheckRoute:
    ApiPublicDiagBusinesscodeTokenCheckRoute,
  ApiPublicDiagBusinesscodeVoiceRoute: ApiPublicDiagBusinesscodeVoiceRoute,
  ApiPublicDiagCallStatusRoute: ApiPublicDiagCallStatusRoute,
  ApiPublicEmailCampaignsTickRoute: ApiPublicEmailCampaignsTickRoute,
  ApiPublicEmailFlowsTickRoute: ApiPublicEmailFlowsTickRoute,
  ApiPublicHooksCashbackCatchupRoute: ApiPublicHooksCashbackCatchupRoute,
  ApiPublicHooksDispatchRoute: ApiPublicHooksDispatchRoute,
  ApiPublicHooksMorningCheckRoute: ApiPublicHooksMorningCheckRoute,
  ApiPublicHooksOrchestrateRoute: ApiPublicHooksOrchestrateRoute,
  ApiPublicHooksRecoveryRoute: ApiPublicHooksRecoveryRoute,
  ApiPublicHooksSmsRefreshStatusRoute: ApiPublicHooksSmsRefreshStatusRoute,
  ApiPublicHooksWebhookReplayRoute: ApiPublicHooksWebhookReplayRoute,
  ApiPublicHooksWhatsappResumeRoute: ApiPublicHooksWhatsappResumeRoute,
  ApiPublicMetaSyncTickRoute: ApiPublicMetaSyncTickRoute,
  ApiPublicPrecallDispatchRoute: ApiPublicPrecallDispatchRoute,
  ApiPublicShortioSyncRoute: ApiPublicShortioSyncRoute,
  ApiPublicWebhookEventoRoute: ApiPublicWebhookEventoRoute,
  ApiPublicEmailImgAssetIdFilenameRoute: ApiPublicEmailImgAssetIdFilenameRoute,
  ApiPublicInfobipVoiceCmlRoute: ApiPublicInfobipVoiceCmlRoute,
  ApiPublicInfobipVoiceEventsRoute: ApiPublicInfobipVoiceEventsRoute,
  ApiPublicWebhookTokenEventoRoute: ApiPublicWebhookTokenEventoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
